In [7]:
import geopandas as gpd
import pandas as pd
from libpysal.weights import fuzzy_contiguity

import sys
sys.path.append('../')
from create_yearMonthID import create_yearMonthID

from pytictoc import TicToc
t = TicToc()

In [16]:
# Shapefile of polygons
pol_fp = '../../data/testing_buffers_spatial/MBfogo_c10_cell_32deg_polygons_2019.shp'

In [17]:
pol = gpd.read_file(pol_fp)

In [18]:
# Converting to metre CRS
print("Converting polygon's CRS")
pol = pol.to_crs('epsg:5880')

Converting polygon's CRS

In [29]:
W.component_labels[len(W.component_labels)-1]

1832

In [43]:
pols_idd = []
last_W = -1
for month in range(1, 12+1):
    t.tic()
    print('Identifying connected components for month {}'.format(month))

    # Subsetting polygons mapped on month
    pol_month = pol[pol['month'] == month]

    # Identifying the polygons that are within a distance from one another
    W = fuzzy_contiguity(pol_month, buffering = True, buffer = 30, silence_warnings = True)
    
    # Correcting to accumulate index through months
    connected_ids = W.component_labels + last_W + 1
    
    pol_month['connected_ids'] = connected_ids
    
    pols_idd.append(pol_month)
    
    # Updating the last weight position
    last_W = connected_ids[len(connected_ids)-1]
    
    del pol_month, W, connected_ids
    
    t.toc('Connected components for month {} identified in'.format(month))
    
pols_idd = gpd.GeoDataFrame(pd.concat(pols_idd))

Identifying connected components for month 1
Connected components for month 1 identified in 0.147504 seconds.
Identifying connected components for month 2

C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Connected components for month 2 identified in 0.101999 seconds.
Identifying connected components for month 3
Connected components for month 3 identified in 0.142093 seconds.
Identifying connected components for month 4
Connected components for month 4 identified in 0.076096 seconds.
Identifying connected components for month 5

C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Connected components for month 5 identified in 0.582549 seconds.
Identifying connected components for month 6

C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Connected components for month 6 identified in 2.447857 seconds.
Identifying connected components for month 7

C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Connected components for month 7 identified in 8.917496 seconds.
Identifying connected components for month 8

C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Connected components for month 8 identified in 37.462264 seconds.
Identifying connected components for month 9

C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Connected components for month 9 identified in 113.047639 seconds.
Identifying connected components for month 10

C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Connected components for month 10 identified in 1.636370 seconds.
Identifying connected components for month 11

C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\geopandas\geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)

Connected components for month 11 identified in 0.927506 seconds.
Identifying connected components for month 12
Connected components for month 12 identified in 0.214505 seconds.

C:\Users\scat8298\.conda\envs\geo_env\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [48]:
pols_idd.tail(50)

,ID,year,month,geometry,connected_ids
227849,201912_1626367,2019,12,"POLYGON ((5653211.549 8810006.854, 5653241.025...",74242
227850,201912_1626368,2019,12,"POLYGON ((5654220.578 8808818.360, 5654250.052...",74243
227851,201912_1626369,2019,12,"POLYGON ((5652038.278 8808800.701, 5652067.753...",74244
227852,201912_1626370,2019,12,"MULTIPOLYGON (((5652092.598 8808559.875, 56520...",74244
227853,201912_1626371,2019,12,"POLYGON ((5654714.678 8808449.088, 5654744.153...",74245
227854,201912_1626372,2019,12,"MULTIPOLYGON (((5654890.944 8808415.689, 56548...",74245
227855,201912_1626373,2019,12,"POLYGON ((5650959.269 8807892.445, 5650988.743...",74246
227856,201912_1626374,2019,12,"POLYGON ((5650811.321 8807865.333, 5650870.269...",74247
227857,201912_1626375,2019,12,"POLYGON ((5650366.900 8807754.034, 5650396.374...",74248
227858,201912_1626376,2019,12,"POLYGON ((5655524.832 8807654.023, 5655554.306...",74249
227859,201912_1626377,2019,12,"POLYGON ((5649389.068 8807503.169, 5649448.016...",74250
227860,201912_1626378,2019,12,"POLYGON ((5653274.952 8807188.211, 5653304.425...",74251
227861,201912_1626379,2019,12,"POLYGON ((5650954.375 8851260.279, 5650983.886...",74252
227862,201912_1626380,2019,12,"POLYGON ((5655976.707 8849877.628, 5656006.217...",74253
227863,201912_1626381,2019,12,"POLYGON ((5665370.458 8834771.112, 5665458.951...",74254
227864,201912_1626382,2019,12,"POLYGON ((5665541.669 8834468.028, 5665571.166...",74255
227865,201912_1626383,2019,12,"POLYGON ((5691886.310 8848975.045, 5691945.330...",74256
227866,201912_1626384,2019,12,"POLYGON ((5691791.855 8848677.004, 5691821.365...",74257
227867,201912_1626385,2019,12,"POLYGON ((5677525.305 8846737.895, 5677554.813...",74258
227868,201912_1626386,2019,12,"POLYGON ((5675577.796 8846775.697, 5675695.827...",74259
227869,201912_1626387,2019,12,"POLYGON ((5680351.897 8844853.734, 5680469.921...",74260
227870,201912_1626388,2019,12,"POLYGON ((5679681.957 8842288.117, 5679711.461...",74261
227871,201912_1626389,2019,12,"POLYGON ((5679828.305 8842225.282, 5679857.809...",74262
227872,201912_1626390,2019,12,"POLYGON ((5675898.237 8840473.049, 5676016.246...",74263
227873,201912_1626391,2019,12,"MULTIPOLYGON (((5677709.452 8838008.972, 56777...",74264
227874,201912_1626392,2019,12,"POLYGON ((5677796.780 8837947.292, 5677826.280...",74265
227875,201912_1626393,2019,12,"POLYGON ((5679064.112 8837862.463, 5679093.612...",74266
227876,201912_1626394,2019,12,"POLYGON ((5675148.475 8836829.762, 5675177.974...",74267
227877,201912_1626395,2019,12,"POLYGON ((5678793.513 8834599.440, 5678823.010...",74268
227878,201912_1626396,2019,12,"POLYGON ((5673137.903 8833600.972, 5673255.889...",74269
227879,201912_1626397,2019,12,"POLYGON ((5673785.654 8833528.345, 5673933.136...",74270
227880,201912_1626398,2019,12,"POLYGON ((5670834.266 8833496.002, 5671040.741...",74271
227881,201912_1626399,2019,12,"POLYGON ((5673252.965 8833448.814, 5673400.447...",74269
227882,201912_1626400,2019,12,"POLYGON ((5671036.078 8833252.225, 5671065.574...",74271
227883,201912_1626401,2019,12,"POLYGON ((5673804.616 8832988.294, 5673922.600...",74272
227884,201912_1626402,2019,12,"POLYGON ((5671177.145 8832919.686, 5671206.641...",74271
227885,201912_1626403,2019,12,"MULTIPOLYGON (((5671321.124 8832736.993, 56712...",74273
227886,201912_1626404,2019,12,"POLYGON ((5671787.217 8832428.089, 5671934.694...",74274
227887,201912_1626405,2019,12,"POLYGON ((5673261.403 8832369.299, 5673408.880...",74275
227888,201912_1626406,2019,12,"POLYGON ((5671191.473 8832139.903, 5671220.969...",74276
227889,201912_1626407,2019,12,"POLYGON ((5671364.942 8831956.633, 5671423.932...",74276
227890,201912_1626408,2019,12,"POLYGON ((5689752.386 8826314.513, 5689781.876...",74277
227891,201912_1626409,2019,12,"POLYGON ((5680966.685 8823641.676, 5680996.173...",74278
227892,201912_1626410,2019,12,"POLYGON ((5652238.164 8806938.569, 5652267.638...",74279
227893,201912_1626411,2019,12,"POLYGON ((5612479.588 8763204.864, 5612509.022...",74280
227894,201912_1626412,2019,12,"POLYGON ((5465556.261 8854338.545, 5465615.289...",74281
227895,201912_1626413,2019,12,"POLYGON ((5465496.835 8854309.444, 5465526.350...",74281
227896,201912_1645243,2019,12,"POLYGON ((5691818.858 8793221.356, 5691817.614...",74282
227897,201912_1645262,2019,12,"POLYGON ((5402696.445 8677765.833, 5402725.798...",74283
227898,201912_1645283,2019,12,"POLYGON ((5341771.040 8782624.400, 5341829.943...",74284

In [45]:
# On the one hand, we create the CSV lookup table
lookup = pols_idd[['ID','year','month','connected_ids']]

In [46]:
lookup['connected_ids'].unique()

array([    0,     1,     2, ..., 74282, 74283, 74284])

In [42]:
lookup['connected_ids'].unique()

array([    0,     1,     2, ..., 48274, 48275, 48276])

In [47]:
# The, also, create a unique ID for each new ID
new_ids = lookup.drop(columns = ['ID']).drop_duplicates(subset = 'connected_ids').reset_index(drop = True)
new_ids

       year  month  connected_ids
0      2019      1              0
1      2019      1              1
2      2019      1              2
3      2019      1              3
4      2019      1              4
...     ...    ...            ...
74280  2019     12          74280
74281  2019     12          74281
74282  2019     12          74282
74283  2019     12          74283
74284  2019     12          74284

[74285 rows x 3 columns]

In [49]:
new_ids = create_yearMonthID(new_ids).reset_index()
new_ids = new_ids.rename(columns = {'ID': 'ID_sjoin'})

In [50]:
new_ids

           ID_sjoin  year  month  connected_ids
0      201901_00000  2019      1              0
1      201901_00001  2019      1              1
2      201901_00002  2019      1              2
3      201901_00003  2019      1              3
4      201901_00004  2019      1              4
...             ...   ...    ...            ...
74280  201912_74280  2019     12          74280
74281  201912_74281  2019     12          74281
74282  201912_74282  2019     12          74282
74283  201912_74283  2019     12          74283
74284  201912_74284  2019     12          74284

[74285 rows x 4 columns]

In [51]:
# THis new datafrme, we merge it back to lookup
lookup = lookup.merge(new_ids[['ID_sjoin','connected_ids']], on = ['connected_ids'], how = 'left')
lookup

                    ID  year  month  connected_ids      ID_sjoin
0       201901_0006919  2019      1              0  201901_00000
1       201901_0006920  2019      1              1  201901_00001
2       201901_0006921  2019      1              2  201901_00002
3       201901_0006922  2019      1              3  201901_00003
4       201901_0006923  2019      1              4  201901_00004
...                ...   ...    ...            ...           ...
227894  201912_1626412  2019     12          74281  201912_74281
227895  201912_1626413  2019     12          74281  201912_74281
227896  201912_1645243  2019     12          74282  201912_74282
227897  201912_1645262  2019     12          74283  201912_74283
227898  201912_1645283  2019     12          74284  201912_74284

[227899 rows x 5 columns]

In [ ]:
# Now we could drop the connected_ids column. We already have the lookup we wanted that relates the original polygons to the new ones.

In [57]:
# Then, on the other hand, we carry out spatial joins. 
# I think, we first join the new ids back to the shapefile, then we do a spatial join based on the ID_sjoin
pols_idd = pols_idd.merge(lookup, how = 'left')
pols_idd.head(40)

,ID,year,month,geometry,connected_ids,ID_sjoin
0,201901_0006919,2019,1,"POLYGON ((5598431.661 8959966.525, 5598461.260...",0,201901_00000
1,201901_0006920,2019,1,"POLYGON ((5541766.699 8981385.281, 5541796.315...",1,201901_00001
2,201901_0006921,2019,1,"POLYGON ((5541917.210 8951764.210, 5541976.397...",2,201901_00002
3,201901_0006922,2019,1,"POLYGON ((5538582.961 8963119.821, 5538612.563...",3,201901_00003
4,201901_0006923,2019,1,"POLYGON ((5533708.419 8959597.439, 5533738.018...",4,201901_00004
5,201901_0006924,2019,1,"POLYGON ((5533558.360 8959449.938, 5533587.959...",5,201901_00005
6,201901_0006925,2019,1,"POLYGON ((5537786.324 8952689.959, 5537875.106...",6,201901_00006
7,201901_0006926,2019,1,"POLYGON ((5541143.541 8981304.076, 5541202.772...",7,201901_00007
8,201901_0006927,2019,1,"MULTIPOLYGON (((5540339.829 8981015.913, 55403...",8,201901_00008
9,201901_0006928,2019,1,"POLYGON ((5540513.838 8980744.274, 5540543.453...",9,201901_00009
10,201901_0006929,2019,1,"POLYGON ((5520747.301 8975536.712, 5520776.912...",10,201901_00010
11,201901_0006930,2019,1,"POLYGON ((5530533.911 8965593.982, 5530563.515...",11,201901_00011
12,201901_0006931,2019,1,"MULTIPOLYGON (((5528746.689 9002530.363, 55287...",12,201901_00012
13,201901_0006932,2019,1,"POLYGON ((5528596.574 9002382.771, 5528626.205...",13,201901_00013
14,201901_0006933,2019,1,"MULTIPOLYGON (((5528002.773 9002300.817, 55280...",14,201901_00014
15,201901_0006934,2019,1,"POLYGON ((5528221.412 9000892.091, 5528251.043...",15,201901_00015
16,201901_0006935,2019,1,"POLYGON ((5527357.830 9000574.387, 5527387.460...",16,201901_00016
17,201901_0006936,2019,1,"POLYGON ((5527416.698 9000543.703, 5527446.328...",16,201901_00016
18,201901_0006937,2019,1,"POLYGON ((5526971.075 9000459.807, 5527030.335...",17,201901_00017
19,201901_0006938,2019,1,"POLYGON ((5526798.653 8998607.558, 5526828.281...",18,201901_00018
20,201901_0006939,2019,1,"POLYGON ((5526283.610 8997746.885, 5526313.238...",19,201901_00019
21,201901_0006940,2019,1,"POLYGON ((5526251.631 8997567.837, 5526281.259...",20,201901_00020
22,201901_0006941,2019,1,"POLYGON ((5526250.847 8997508.025, 5526280.475...",20,201901_00020
23,201901_0006942,2019,1,"MULTIPOLYGON (((5526338.946 8997447.046, 55263...",20,201901_00020
24,201901_0006943,2019,1,"POLYGON ((5526515.928 8997384.901, 5526575.184...",21,201901_00021
25,201901_0006944,2019,1,"POLYGON ((5534806.478 8996886.324, 5534865.732...",22,201901_00022
26,201901_0006945,2019,1,"POLYGON ((5520676.313 8990402.585, 5520705.935...",23,201901_00023
27,201901_0006946,2019,1,"MULTIPOLYGON (((5546693.102 9019195.409, 55466...",24,201901_00024
28,201901_0006947,2019,1,"POLYGON ((5546722.347 9019165.100, 5546751.991...",24,201901_00024
29,201901_0006948,2019,1,"POLYGON ((5531811.005 9023907.875, 5531840.652...",25,201901_00025
30,201901_0006949,2019,1,"MULTIPOLYGON (((5532452.044 9023032.117, 55324...",26,201901_00026
31,201901_0006950,2019,1,"POLYGON ((5532537.120 9022731.884, 5532596.412...",27,201901_00027
32,201901_0006951,2019,1,"MULTIPOLYGON (((5531229.217 9022479.567, 55311...",28,201901_00028
33,201901_0006952,2019,1,"POLYGON ((5523072.887 9015316.009, 5523102.528...",29,201901_00029
34,201901_0006953,2019,1,"POLYGON ((5521589.702 9015245.247, 5521619.343...",30,201901_00030
35,201901_0006954,2019,1,"POLYGON ((5523775.838 9014648.984, 5523805.478...",31,201901_00031
36,201901_0006955,2019,1,"POLYGON ((5523656.893 9014620.600, 5523686.534...",32,201901_00032
37,201901_0006956,2019,1,"POLYGON ((5523537.949 9014592.216, 5523567.589...",33,201901_00033
38,201901_0006957,2019,1,"POLYGON ((5523622.271 9014232.216, 5523651.911...",34,201901_00034
39,201901_0006958,2019,1,"POLYGON ((5524773.621 9013858.502, 5524892.180...",35,201901_00035

In [54]:
# Now, spatial join
t.tic()
new_pols = pols_idd[['ID_sjoin','year','month','geometry']].dissolve(by = 'ID_sjoin').reset_index()
t.toc()

Elapsed time is 70.722269 seconds.

In [55]:
new_pols.head()

,ID_sjoin,geometry,year,month
0,201901_00000,"POLYGON ((5598431.661 8959966.525, 5598461.260...",2019,1
1,201901_00001,"POLYGON ((5541766.699 8981385.281, 5541796.315...",2019,1
2,201901_00002,"POLYGON ((5541917.210 8951764.210, 5541976.397...",2019,1
3,201901_00003,"POLYGON ((5538582.961 8963119.821, 5538612.563...",2019,1
4,201901_00004,"POLYGON ((5533708.419 8959597.439, 5533738.018...",2019,1

In [56]:
new_pols.tail()

,ID_sjoin,geometry,year,month
74280,201912_74280,"POLYGON ((5612479.588 8763204.864, 5612509.022...",2019,12
74281,201912_74281,"MULTIPOLYGON (((5465526.350 8854309.051, 54655...",2019,12
74282,201912_74282,"POLYGON ((5691818.858 8793221.356, 5691817.614...",2019,12
74283,201912_74283,"POLYGON ((5402696.445 8677765.833, 5402725.798...",2019,12
74284,201912_74284,"POLYGON ((5341771.040 8782624.400, 5341829.943...",2019,12